@startuml

left to right direction

skinparam monochrome true
skinparam classAttributeIconSize 0
hide circle

class Renderer

abstract class Mesh
class StaticMesh
class SkinnedMesh

Mesh <|-- StaticMesh
Mesh <|-- SkinnedMesh

abstract class Light
class DirectionlLight
class PointLight
class SpotLight

Light <|-- DirectionlLight
Light <|-- PointLight
Light <|-- SpotLight



@enduml